In [2]:
import numpy as np


In [3]:
A = np.array([1, 2, 3, 4])
B = np.array([2, 4, 6, 8])
def problem_1a (A, B):
    return A + B

print(problem_1a(A, B))

[ 3  6  9 12]


In [4]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
B = np.array(
    [[4, 5, 6],
    [4, 6, 8],
    [5, 7, 9]]
    )
C = np.array(
    [[1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]]
    )
def problem_1b (A, B, C):
    #matrix multiplication
    return ((A@B) - C)

print(problem_1b(A, B, C))

[[26 37 48]
 [52 74 96]
 [38 55 72]]


In [6]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
B = np.array(
    [[4, 5, 6],
    [4, 6, 8],
    [5, 7, 9]]
    )
C = np.array(
    [[1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]]
    )
def problem_1c (A, B, C):
    #element-wise multiplication
    return ((A * B) + C.T)

print(problem_1c(A, B, C))

[[ 5 12 21]
 [ 9 26 51]
 [ 6 23 48]]


In [7]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])
def problem_1d (x, y):
    #inner product
    return np.inner(x, y)

print(problem_1d(x, y))

60


In [8]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
def problem_1e (A):
    return np.zeros(np.shape(A))

print(problem_1e(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
A = np.array(
    [[1, 1, 3],
    [2, 1, 6],
    [4, 1, 5]]
    )
x = np.array([1, 2, 3])
def problem_1f (A, x):
    return np.linalg.solve(A, x)


print(problem_1f(A, x))

[ 5.71428571e-01 -7.40148683e-17  1.42857143e-01]


In [17]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
x = np.array([1, 2, 3])
def problem_1g (A, x):
    return (np.linalg.solve(A.T, x.T)).T

print(problem_1g(A, x))

[-1.  1. -0.]


In [21]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
alpha = 2
def problem_1h (A, alpha):
    return A + (alpha * np.eye(A.shape[1]))

print(problem_1h(A, alpha))

[[4. 2. 3.]
 [3. 6. 6.]
 [4. 3. 7.]]


In [24]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
i = 1
def problem_1i (A, i):
    return np.sum(A[i, 0::2])

print(problem_1i(A, i))

9


In [28]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
c = 4
d = 6 
def problem_1j (A, c, d):
    arr = A[((c <= A) & (A <= d))]
    total = arr.shape
    return np.sum(arr) / total

print(problem_1j (A, c, d)) 

[4.75]


In [20]:

def problem_1k (A, k):    
    return ...

print(problem_1k(A, k))

[11.48565082  3.37543563  6.13891355]
[2 0]
[[ 0.12042721  0.27500502]
 [-0.3882481   0.47337791]
 [ 0.91365239  0.83683069]]


In [ ]:
def problem_1l (x, k, m, s):    
    return ...

print(problem_1l(x, k, m, s))

In [ ]:
def problem_1m (A):    
    return ...

print(problem_1m(A))

In [ ]:
def problem_1n (x):    
    return ...

print(problem_1n(x))

In [ ]:
def problem_1o (x, k):    
    return ...

print(problem_1o(x, k))

In [27]:
def problem_1p (X):    
    return ...

print(problem_1p(X))

[[0.         2.44948974 5.47722558]
 [2.44948974 0.         4.        ]
 [5.47722558 4.         0.        ]]


In [ ]:
def linear_regression (X_tr, y_tr):    
    ...

print(linear_regression(X_tr, y_tr))

In [ ]:
def train_age_regressor ():    
    # Load data    
    X_tr = np.reshape(np.load("age_regression_Xtr.npy"), (-1, 48*48))    
    ytr = np.load("age_regression_ytr.npy")    
    X_te = np.reshape(np.load("age_regression_Xte.npy"), (-1, 48*48))    
    yte = np.load("age_regression_yte.npy")
    w = linear_regression(X_tr, ytr)    
    # Report fMSE cost on the training and testing data (separately)    
    # ...