In [1]:
import numpy as np
# remember:
# a[start:stop:step]
# a[row,col : row,col] ex. a[,2:] start from 3rd col

In [2]:
A = np.array([1, 2, 3, 4])
B = np.array([2, 4, 6, 8])
def problem_1a (A, B):
    return A + B

print(problem_1a(A, B))

[ 3  6  9 12]


In [3]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
B = np.array(
    [[4, 5, 6],
    [4, 6, 8],
    [5, 7, 9]]
    )
C = np.array(
    [[1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]]
    )
def problem_1b (A, B, C):
    #matrix multiplication
    return ((A@B) - C)

print(problem_1b(A, B, C))

[[26 37 48]
 [52 74 96]
 [38 55 72]]


In [4]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
B = np.array(
    [[4, 5, 6],
    [4, 6, 8],
    [5, 7, 9]]
    )
C = np.array(
    [[1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]]
    )
def problem_1c (A, B, C):
    #element-wise multiplication
    return ((A * B) + C.T)

print(problem_1c(A, B, C))

[[ 5 12 21]
 [ 9 26 51]
 [ 6 23 48]]


In [5]:
x = np.array([[1, 2, 3, 4]])
y = np.array([[2, 4, 6, 8]])
def problem_1d (x, y):
    #inner product
    return np.inner(x, y)

print(problem_1d(x, y))

[[60]]


In [6]:
A = np.array(
    [[1, 2, 3],
    [2, 4, 6],
    [1, 3, 5]]
    )
def problem_1e (A):
    return np.zeros(np.shape(A))

print(problem_1e(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
A = np.array(
    [[1, 1, 3],
    [2, 1, 6],
    [4, 1, 5]]
    )
x = np.array([[1, 2, 3]]).T
def problem_1f (A, x):
    return np.linalg.solve(A, x)


print(problem_1f(A, x))

[[ 5.71428571e-01]
 [-7.40148683e-17]
 [ 1.42857143e-01]]


In [8]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
x = np.array([1, 2, 3])
def problem_1g (A, x):
    return (np.linalg.solve(A.T, x.T)).T

print(problem_1g(A, x))

[-1.  1. -0.]


In [9]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
alpha = 2
def problem_1h (A, alpha):
    return A + (alpha * np.eye(A.shape[1]))

print(problem_1h(A, alpha))

[[4. 2. 3.]
 [3. 6. 6.]
 [4. 3. 7.]]


In [10]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
i = 1
def problem_1i (A, i):
    return np.sum(A[i, 0::2])

print(problem_1i(A, i))

9


In [11]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )
c = 4
d = 6 
def problem_1j (A, c, d):
    arr = A[((c <= A) & (A <= d))]
    total = arr.shape
    return np.sum(arr) / total

print(problem_1j (A, c, d)) 

[4.75]


In [12]:
A = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )

k = 1
def problem_1k (A, k):
    eigen_value, eigen_vector = np.linalg.eig(A)
    sort_eig_val_idx = np.argsort(eigen_value)[::-1][:k]
    return eigen_vector[:,sort_eig_val_idx]

print(problem_1k(A, k))

[[0.36695707+0.j]
 [0.70001122+0.j]
 [0.61263921+0.j]]


In [13]:

x = (np.array([[1, 3, 5]])).T
k = 1
m = 1 
s = 2

def problem_1l (x, k, m, s):    
    x_row, x_col = x.shape
    z = np.ones((x_row, x_col))
    I = np.eye(x_row)
    mu = x + (m * z)
    sigma = np.sqrt(s * I)
    return np.random.multivariate_normal(np.squeeze(mu), sigma, k).T

print(problem_1l(x, k, m, s))

[[0.99770917]
 [4.31438243]
 [6.17317409]]


In [14]:
A = np.array(
    [[2, 2, 3, 4, 5],
    [3, 4, 6, 7, 6],
    [4, 3, 5, 2, 9]]
    )
A_1 = np.array(
    [[2, 2, 3],
    [3, 4, 6],
    [4, 3, 5]]
    )

def problem_1m (A):    
    idx = np.random.permutation(A.shape[0])
    return A[idx,:]

print(problem_1m(A))

[[3 4 6 7 6]
 [2 2 3 4 5]
 [4 3 5 2 9]]


In [15]:
x = np.array([[1, 2, 3, 4]])
def problem_1n (x):
    return (x[:] - np.mean(x)) / np.std(x)   

print(problem_1n(x))

[[-1.34164079 -0.4472136   0.4472136   1.34164079]]


In [16]:
x = np.array([1, 2, 3, 4])
print("x: \n", x)
x_1 = np.arange(6).reshape(2, 3)
# print("x_1: \n", x_1)
x_2 = np.arange(6).reshape(3, 2)
# print("x_2: \n", x_2)
# x_3 = np.array([
#     [1, 2, 3, 4],
#     [2, 3, 4, 5]]
#     )
# print("x_3: \n", x_3)
# k = [2, 3]
k = 4
def problem_1o (x, k):
    x_2d = np.atleast_2d(x)
    return (np.repeat(x_2d, k, 0)).T

print("Problem with x \n", problem_1o(x, k))
# print("Problem with x_1 \n", problem_1o(x_1, k))
# print("Problem with x_2 \n", problem_1o(x_2, k))

x: 
 [1 2 3 4]
Problem with x 
 [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [17]:
X = np.array([1, 2, 3, 4])
X_2 = np.arange(4).reshape(1, 4)
X_3 = np.arange(8).reshape(2, 4)
X_4 = np.arange(12).reshape(3, 4)

def problem_1p (X): 
    X_a = (np.atleast_2d(X))
    print("\nthis is X_a: \n", X_a)

    X_b = (np.atleast_2d(X))
    print("\nthis is X_b: \n", X_b)

    x_a = np.atleast_3d(X_a)
    print("\nthis is x_a: \n", x_a)

    x_b = np.swapaxes(np.atleast_3d(X_b), 1, 2)
    print("\nthis is x_b: \n", x_b)

    # tile_a_dim = [3rd dim, 0th index, 1st index]
    # tile_a_dim = [1, 1, 4]

    # tile_b_dim = [3rd dim, 1st index, 0th index] 
    # tile_b_dim = [1, 4, 1]
    tile_a_dim = [1, 1, X_b.shape[1]]
    tile_b_dim = [1, X_a.shape[1], 1]

    A = np.tile(x_a, tile_a_dim)
    print("\nthis is A: \n", A)

    B = np.tile(x_b, tile_b_dim)
    print("\nthis is B: \n", B)

    return np.sqrt(np.sum(np.square(A - B), 0))

print("------------------First test------------------\n")
print("\nThis is output using X: \n", problem_1p(X))

print("\n------------------Second test------------------\n")
print("\nThis is output using X_2: \n", problem_1p(X_2))

print("\n------------------Third test------------------\n")
print("\nThis is output using X_3: \n", problem_1p(X_3))

print("\n------------------Fourth test------------------\n")
print("\nThis is output using X_4: \n", problem_1p(X_4))

------------------First test------------------


this is X_a: 
 [[1 2 3 4]]

this is X_b: 
 [[1 2 3 4]]

this is x_a: 
 [[[1]
  [2]
  [3]
  [4]]]

this is x_b: 
 [[[1 2 3 4]]]

this is A: 
 [[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]]

this is B: 
 [[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

This is output using X: 
 [[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]]

------------------Second test------------------


this is X_a: 
 [[0 1 2 3]]

this is X_b: 
 [[0 1 2 3]]

this is x_a: 
 [[[0]
  [1]
  [2]
  [3]]]

this is x_b: 
 [[[0 1 2 3]]]

this is A: 
 [[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]]

this is B: 
 [[[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]

This is output using X_2: 
 [[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]]

------------------Third test------------------


this is X_a: 
 [[0 1 2 3]
 [4 5 6 7]]

this is X_b: 
 [[0 1 2 3]
 [4 5 6 7]]

this is x_a: 
 [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]

this is x_b: 
 [

In [18]:
def linear_regression (X_tr, y_tr):    
    ...

print(linear_regression(X_tr, y_tr))

NameError: name 'X_tr' is not defined

In [ ]:
def train_age_regressor ():    
    # Load data    
    X_tr = np.reshape(np.load("age_regression_Xtr.npy"), (-1, 48*48))    
    ytr = np.load("age_regression_ytr.npy")    
    X_te = np.reshape(np.load("age_regression_Xte.npy"), (-1, 48*48))    
    yte = np.load("age_regression_yte.npy")
    w = linear_regression(X_tr, ytr)    
    # Report fMSE cost on the training and testing data (separately)    
    # ...