In [1]:
import numpy as np
A_var = np.array([
    [5, 2, 1],
    [6, 8, 0],
    [2, 5, 8]
    ])
B_var = np.array([
    [5, 3, 2],
    [7, 9, 1],
    [3, 6, 9]
    ])
C_var = np.array([
    [6, 3, 2],
    [8, 0, 2],
    [4, 7, 0]
    ])


x = np.array([5, 2, 1, 6, 8])

x_1 = np.array([[5, 2, 1], 
                [6, 8, 8]])

x_2 = np.array([[5, 2, 1], 
                [6, 8, 8]])

x_3 = np.array([5, 2, 1])

y = np.array([5, 3, 2, 7, 9])

y_1 = np.array([[5, 3, 2], 
                [7, 9, 4]])

y_2 = np.array([[5, 3, 2], 
                [7, 9, 4]])

matrix = np.array([
    [1, 2, 0],
    [2, 2, 0],
    [3, 2, 0],
    [4, 2, 0]
    ])

matrix_two = np.array([
    [4, 3, 2, 1],
    [2, 2, 2, 2],
    [0, 0, 0, 0]
    ])

In [2]:
#correct
def problem_1a (A, B):
    return A + B

a = problem_1a(A_var, B_var)
print(problem_1a(A_var, B_var))

[[10  5  3]
 [13 17  1]
 [ 5 11 17]]


In [3]:
#correct
def problem_1b (A, B, C):
    return (np.dot(A, B) - C)

print(problem_1b(A_var, B_var, C_var))

[[36 36 19]
 [78 90 18]
 [65 92 81]]


In [4]:
#correct
def problem_1c (A, B, C):
    return ((A * B) + C.T)

print(problem_1c(A_var, B_var, C_var))

[[31 14  6]
 [45 72  7]
 [ 8 32 72]]


In [5]:
#not correct I think
def problem_1d (x, y):
    return np.inner(x, y)

print(problem_1d(x_1, y_1))

[[ 33  57]
 [ 70 146]]


In [6]:
#correct
def problem_1e (A):
    return np.zeros(np.shape(A_var))

print(problem_1e(A_var))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#not correct
def problem_1f (A, x):
    return np.linalg.solve(A, x)

def test_1f(A, x, b):
    pass_bool = np.allclose(np.dot(A, x), b)
    if pass_bool == True:
        print("Test passed")
    else:
        print("Mission Failed, You'll Get Em Next Time")

b = problem_1f(A_var, x_3)
print("problem 1f \n", b)
test_1f(A_var, x_3, b)

problem 1f 
 [ 1.21848739 -0.66386555  0.23529412]
Mission Failed, You'll Get Em Next Time


In [8]:
#not correct
def problem_1g (A, x):
    return (np.linalg.solve(A.T, x.T)).T

def test_1g(A, x, b_2):
    pass_bool = np.allclose(np.dot(A, x), b_2)
    if pass_bool == True:
        print("Test passed")
    else:
        print("Mission Failed, You'll Get Em Next Time")

b_2 = problem_1f(A_var, x_3)
print("problem 1f \n", b_2)
test_1f(A_var, x_3, b_2)

problem 1f 
 [ 1.21848739 -0.66386555  0.23529412]
Mission Failed, You'll Get Em Next Time


In [9]:
#correct
def problem_1h (A, alpha):
    num_rows, num_cols = A.shape
    print("This is A \n", A)
    print("\nThis is I \n", np.eye(num_rows))
    return A + (np.eye(num_rows) * alpha)

print("\nThe answer for 1h \n", problem_1h(A_var, 5))

This is A 
 [[5 2 1]
 [6 8 0]
 [2 5 8]]

This is I 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

The answer for 1h 
 [[10.  2.  1.]
 [ 6. 13.  0.]
 [ 2.  5. 13.]]


In [10]:
#correct
def problem_1i (A, i):
    return np.sum(A[i, ::2])

print(problem_1i(A_var, 2))

10


In [11]:
#correct
def problem_1j (A, c, d):
    b = np.where(np.logical_and(c <= A, A <= d))
    return np.mean(A[b])

print(problem_1j (A_var, 2, 6)) 

4.0


In [20]:
#correct
def problem_1k (A, k):
    eigen_value, eigen_vector = np.linalg.eig(A) #get eigenvalues and vectors
    descen_arr_indices = eigen_value.argsort() #sort indices in descending order
    matching_indices = descen_arr_indices[len(descen_arr_indices) - k:]
    return eigen_vector[:,matching_indices] #use indices to get respective eigen vectors 

print(problem_1k(A_var, 2)) 

[11.48565082  3.37543563  6.13891355]
[2 0]
[[ 0.12042721  0.27500502]
 [-0.3882481   0.47337791]
 [ 0.91365239  0.83683069]]


In [ ]:
def problem_1l (x, k, m, s):
    return np.random.multivariatenormal(x+m, np.eye(x.shape[0]) * s, k).T

#x_row, x_col  = x.shape()
#m_z =  m * np.ones(x.shape)
#s_i = s * np.eye(x_row, k)
#n_k = np.random.multivariatenormal(x + m_z, s_i)
#return n_k

In [ ]:
def problem_1m (A):
    return np.random.permutation(A)

In [ ]:
def problem_1n (x):
    x_bar = np.mean(x)
    sigma = np.std(x)
    y_vec = []
    for i in range(len(x)):
        x_i = x[i]
        y_i =  (x_i - x_bar) / sigma 
        y_vec.append(y_i)

    return y_vec

In [ ]:
def problem_1o (x, k):
    return np.repeat(np.atleast_2d(x),k)

In [27]:
#correct
def problem_1p (X):
    m, n = np.shape(X)
    three_dim_mat = np.repeat(np.atleast_3d(X), n, axis=2)
    swap_mat = np.swapaxes(three_dim_mat, 1, 2)
    D = np.sqrt(np.sum(np.square(three_dim_mat-swap_mat), axis=0))
    return D

print(problem_1p(matrix))

[[0.         2.44948974 5.47722558]
 [2.44948974 0.         4.        ]
 [5.47722558 4.         0.        ]]


In [ ]:
def linear_regression (X_tr, y_tr):
    X_t = X_tr.T
    X_y = np.matmul(X_tr.T, y_tr)
    X_XT = np.matmul(X_t, X_tr)
    return np.linalg.solve(X_XT, X_y)

In [ ]:
def mean_square_error(y_hat, y):
    dist_diff = np.square(y_hat-y)
    err = np.mean(dist_diff)
    return err

In [ ]:
def train_age_regressor():
    # Load data
    X_tr = np.reshape(np.load("age_regression_Xtr.npy"), (-1, 48*48))
    ytr = np.load("age_regression_ytr.npy")
    X_te = np.reshape(np.load("age_regression_Xte.npy"), (-1, 48*48))
    yte = np.load("age_regression_yte.npy")

    w = linear_regression(X_tr, ytr)
    y_hat_tr = np.matmul(X_tr, w)
    y_hat_te = np.matmul(X_te, w)

    train = mean_square_error(y_hat_tr, ytr)
    test = mean_square_error(y_hat_te, yte)

    return train, test


    # Report fMSE cost on the training and testing data (separately)
    # ...

In [ ]:
print(train_age_regressor())