In [36]:
import numpy as np
A = np.array([[
    [5, 2, 1],
    [6, 8, 0],
    [2, 5, 8],
    ]])
B = np.array([[
    [5, 3, 2],
    [7, 9, 1],
    [3, 6, 9],
    ]])
C = np.array([[
    [6, 3, 2],
    [8, 0, 2],
    [4, 7, 0],
    ]])

In [37]:
def problem_1a (A, B):
    return A + B

print(problem_1a(A, B))

[[[10  5  3]
  [13 17  1]
  [ 5 11 17]]]


In [38]:
def problem_1b (A, B, C):
    return (np.dot(A, B)) - C

print(problem_1b(A, B, C))

[[[[36 36 19]
   [34 39 19]
   [38 32 21]]

  [[80 87 18]
   [78 90 18]
   [82 83 20]]

  [[63 96 79]
   [61 99 79]
   [65 92 81]]]]


In [39]:
def problem_1c (A, B, C):
    return (A * B) + (np.transpose(C))

print(problem_1c(A, B, C))

[[[31 12  8]
  [50 80  8]
  [10 34 76]]

 [[28  9  5]
  [42 72  0]
  [13 37 79]]

 [[27  8  4]
  [44 74  2]
  [ 6 30 72]]]


In [ ]:
def problem_1d (x, y):
    return np.dot(np.transpose(x), y)

In [ ]:
def problem_1e (A):
    return np.zeros(np.shape(A))

In [ ]:
def problem_1f (A, x):
    return np.linalg.solve(A, x)

In [ ]:
def problem_1g (A, x):
    return np.linalg.solve(A.T, x.T)

In [ ]:
def problem_1h (A, alpha):
    num_rows, num_cols = A.shape
    return A + (np.eye(num_rows) * alpha)

In [ ]:
def problem_1i (A, i):
    return np.sum(A[i, 1::2])

In [3]:
def problem_1j (A, c, d):
    b = np.where((c <= A and A <= d))
    return np.mean(A[b])

In [ ]:
def problem_1k (A, k):
    eigen_value, eigen_vector = np.linalg.eig(A) #get eigenvalues and vectors
    descen_arr_indices = eigen_value[::-1].argsort() #sort indices in descending order
    return eigen_vector[:,descen_arr_indices[:,:k]] #use indices to get respective eigen vectors 

In [ ]:
x = 
k = 
m = 
s = 
print("This is array A", A)
print("This is array B", B)
print("This is array B", C)

def problem_1l (x, k, m, s):
    x_row, x_col  = x.shape()
    m_z =  m * np.ones(x.shape)
    s_i = s * np.eye(x_row, k)
    n_k = np.random.multivariatenormal(x + m_z, s_i)
    return n_k

In [ ]:
def problem_1m (A):
    return np.random.permutation(A)

In [ ]:
def problem_1n (x):
    x_bar = np.mean(x)
    sigma = np.std(x)
    y_vec = []
    for i in range(len(x)):
        x_i = x[i]
        y_i =  (x_i - x_bar) / sigma 
        y_vec.append(y_i)

    return y_vec

In [ ]:
def problem_1o (x, k):
    return np.repeat(np.atleast_2d(x),k)

In [ ]:
def problem_1p (X):
    return 

In [ ]:
def linear_regression (X_tr, y_tr):
    # set random value for w
    # x is set to pixel value
    #y is set age of the person in picture
    #n is total number of pictures
    #w a scalar that has 1:1 relationship with number of pixels 

    #transpose x
    #multiply X to w
    #subtract y value from y_hat
    #update w
    #repeat until training set is complete 

    #use aquired w matrix to then test values on test set and determine accuracy 
    #use aquired w matrix to then test values on the training set (can be thought of as test set part 2)
    return w

In [ ]:
def train_age_regressor():
    # Load data
    X_tr = np.reshape(np.load("age_regression_Xtr.npy"), (-1, 48*48))
    ytr = np.load("age_regression_ytr.npy")
    X_te = np.reshape(np.load("age_regression_Xte.npy"), (-1, 48*48))
    yte = np.load("age_regression_yte.npy")

    w = linear_regression(X_tr, ytr)

    # Report fMSE cost on the training and testing data (separately)
    # ...